name: flutter_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
#dependencies:
#  vania: ^0.5.0

dependencies:
  shelf:
  shelf_router:
  drift:
  sqlite3:
  path:
  crypto:
  sqlite3_flutter_libs:

dev_dependencies:
  build_runner:
  drift_dev:

